name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --verbose --release
        
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: rua-windows
          path: target/release/rua.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --verbose --release
        
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: rua-linux
          path: target/release/rua

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write # This permission is required to create a release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This will use the tag that triggered the workflow as the release name
          name: Release ${{ github.ref_name }}
          # This will upload both the Windows and Linux executables
          files: |
            dist/rua-windows/rua.exe
            dist/rua-linux/rua